/* SPDX-License-Identifier: MIT
 * Copyright(c) 2022 Darek Stojaczyk
 */

#ifndef SYNERGY_SERIAL_CONFIG
#define SYNERGY_SERIAL_CONFIG

#define CONFIG_HOSTNAME "red"
#define CONFIG_SCREENX 0
#define CONFIG_SCREENY 0
#define CONFIG_SCREENW (1920 * 2)
#define CONFIG_SCREENH 1080
#define CONFIG_SERIAL_TX_SIZE 8
#define CONFIG_SERIAL_MOUSE_INTERVAL_MS 16

#endif /* SYNERGY_SERIAL_CONFIG */